language: node_js
node_js:
  - 0.10
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 #give time to start up

after_success: ./node_modules/coveralls/bin/coveralls.js < coverage/report-lcov/lcov.info

script: ./run-tests.sh
